### ISSUE TITLE
Twitter API loader component

### ISSUE THREAD

**Issue by scabbiaza** [Paqmind/twitto#1]
# Create interface component to load Twitter Frame in timeline

Three basic ways to do this:
1. Load twitter in new page (with reloading or in new tab).
2. Open twitter frame above or below the timeline.
3. Load it in popup.

First way is the simplest but with no usability – we are losing timeline data at least.
Second way is straightforward too, but with good animation between timeline and twitter it can be the solution.
Third way is iffy. From one this term popup has huge negative content, from other side looking on big web applications we can see it's still alive.

### Devices support

It's better to get the answer on this question at the beginning. I suppose twitto should work on all modern browsers and modern devices: desktop, laptop, phones.
Key word is "modern" here. Old devices with old browser could not support all javascript that will be *necessary* for this web app.

**Exploring twitter**

Can we have one solution for all devices? (ok, for all "modern" devices).
Let's look at the twitter. They have desktop version, and versions for iOS and Android as well.
They also have http://mobile.twitter.com that is work differently on different devices: it looks pretty modern on iPad4, but old on old samsung with android.

Desktop and mobile applications are almost free in their choices. 
Mobile version on iPad use ajax, animation etc. 
Mobile version on old devices is very limited: any action requires page reloading.

So the answer is – if you want to have "all" devices support, you'll better to start gathering developers from different platforms.

I suppose we are going to create web application in browser. Let's call it "site", to be simple.

### Choosing terms: popup, modal, dialog ...

There is a lot of confusions in this terms, because libs and frameworks use their differently.

**Bootstrap** has `modal`:
http://getbootstrap.com/javascript/#modals

It often contains header, content and footer, and fills part of the screen with current page content fading.

**Google** calls it `dialog`:
https://www.google.com/design/spec/components/dialogs.html

*Dialogs inform users about critical information, require users to make decisions, or encapsulate multiple tasks within a discrete process. Use dialogs sparingly because they are interruptive in nature—their sudden appearance forces users to stop their current task and refocus on the dialog content.*

Use fullscreen mode or not, it depends from how much information contains the dialog component.

**jQuery Mobile** has `dialog` and `page` elements:
http://demos.jquerymobile.com/1.4.5/transitions/

Dialog is more like confirmation with minimum information in content, similar to `modal` in bootstrap. `Page` is similar to `fullscreen mode dialog` in google guidelines.

I prefer to use jQuery terms.

### About transitions

So back to our twitter frame component and third way: *Load it in popup*.
Because we are going to use Bootstrap framework we can use `modal` component.
It's simple, quick solution and it has good support:
http://getbootstrap.com/getting-started/#support

But what alternatives do we have?

**jQuery Mobile**
*jQuery Mobile is a HTML5-based user interface system designed to make responsive web sites and apps that are accessible on all smartphone, tablet and desktop devices.*

I love this demo:
http://demos.jquerymobile.com/1.4.5/transitions/

To have ability to chose between dialogs and pages and different animation would be great benefit for the project. And they have awesome devices support: 
http://jquerymobile.com/gbs/1.4/

But when we will look closer, we will see they still have issues with `transitions` on some devices.
So if they have, any other will have it. 

Can we close the eyes on it? Maybe we could, but developers do not recommend to use Bootstrap and jQuery Mobile together :confused: :
http://stackoverflow.com/questions/18636919/can-i-use-bootstrap-3-together-with-jquery-mobile

But maybe we can take only this `transition.js` from JQM? 
Did you work with jQuery UI before? It's f**king mess from js and css classes. So leave this idea.

Looking on jQuery Mobile alternatives like http://www.sencha.com/, http://goratchet.com/, http://app-framework-software.intel.com/, you will see - they are frameworks for mobile application *only*.

**Effeckt.css**
https://github.com/h5bp/Effeckt.css

This lib has 9000 stars on github and it says:
*Designing and developing UIs for the mobile web is tricky, but it's extremely difficult to do that while delivering something that performs at 60fps. The best opportunities to getting jank-free transitions on phones/tablets are CSS transition and keyframe animation based, especially tapping into hardware-accelerated transforms and opacity changes.*

Yes, let's stick with pure css! I believe in it. 

But why demo doesn't work on my mobile devices?
http://h5bp.github.io/Effeckt.css/

Both Chrome and Safari are stucking by trying `page load` effect. I updated OS version – didn't help.
In Samsung with Android this page even did not load properly.

**Codrops**
Article from 2013:
http://tympanus.net/Development/PageTransitions/

Looks cool on iPad, doesn't work on Samsung Android, works on Mac Chrome, IE supports only from version 10. WTF?

### Summary

I strongly recommend to stick with the bootstrap's modal and do not f**k the brain.
It will not support in old browsers, but we decided we will not support it.

Later I will try to add `page` effect as in JQM with simplest animation (fade, slide, etc)

**Comment by scabbiaza** [comment]
Can we close this? Btw, if  we remove this repo, we will lose this also :(

**Comment by ivan-kleshnin** [comment]
We will rename it, probably without removal.
