### ISSUE TITLE
Normalize http errors templates

### ISSUE THREAD

**Issue by ivan-kleshnin** [Paqmind/twitto#7]
Look for TODO in **http-errors.css**
Update / improve template as good as we can.

**Comment by scabbiaza** [comment]
Decided to create error templates for this project using wallpapers with Bender.

**Comment by scabbiaza** [comment]
What do you think?
http://puu.sh/fXfZf.png

**Comment by ivan-kleshnin** [comment]
Looks cool! I like it. Why the title is no slab but serif?

**Comment by scabbiaza** [comment]
400:
http://puu.sh/fZKR2.png

401:
http://puu.sh/fZL6y.png

403:
http://puu.sh/fZL9h.png

404:
http://puu.sh/fZKx2.png
(mobile – http://puu.sh/fZKy6.png)

410:
http://puu.sh/fZLbe.png

500:
http://puu.sh/fZLeb.png

503:
http://puu.sh/fZLfW.png

**Comment by ivan-kleshnin** [comment]
Everything is super-cool, except I don't like how messages break on nearly empty screens.
Maybe smaller font size will solve this?

**Comment by scabbiaza** [comment]
Fixed and merged
