### ISSUE TITLE
Page loader

### ISSUE THREAD

**Issue by scabbiaza** [Paqmind/twitto#9]
http://tympanus.net/Development/PageLoadingEffects/
http://tympanus.net/Development/CreativeLoadingEffects/

**Comment by ivan-kleshnin** [comment]
I thought we wanted ajax loaders (spinners) and these are page loaders (transition effects).

**Comment by scabbiaza** [comment]
Yes, this links are for something else.
What do you think about spinner in font-awesome (Animated Icons)?
http://fortawesome.github.io/Font-Awesome/examples/

I love this gear

**Comment by ivan-kleshnin** [comment]
Wow, I'm starting to use that cog right now :)
